# Collect OAM-Repos, Releases-Info and Release-Archive-Assets
# (C) 2025-2026 Cornelius Köpp; For Usage in OpenKNX-Project only
import json
import logging
import os
import zipfile
from io import BytesIO

from defusedxml import ElementTree as ET

from app_config import OamConfig
from app_sizing_stat import AppSizingStat
from github_client import GitHubClient
from model.oam_data import OamRepo
from model.oam_releases import ReleaseAsset, OamReleaseData, OamReleasesData


class ReleaseManager:
    def __init__(self, client: GitHubClient, app_config: OamConfig):
        self.client = client
        self.app_config = app_config

    def fetch_app_repos(self) -> list[OamRepo]:
        """
        Read the info for all public Application Repos (selected by Name) from API and return full data as List.

        :return: list of structured repo data
        """
        repos_data = self.client.get_org_repos()
        app_repos_data = [
            OamRepo(
                name = repo["name"],
                updated_at = repo["updated_at"],
                pushed_at = repo["pushed_at"],
                releases_url = repo["releases_url"],
                repo_url = repo["html_url"],
                archived = repo["archived"],
                description = repo["description"],
                default_branch = repo["default_branch"],
            )
            for repo in repos_data
            if self.app_config.include_repo(repo)
        ]
        return app_repos_data

    def fetch_apps_releases(self, repos_data: list[OamRepo]) -> dict[str, OamReleasesData]:
        releases_data = {}
        for repo in repos_data:
            name = repo.name
            url = repo.releases_url.replace("{/id}", "") # TODO define function?
            logging.info(f"Fetching release data {name} from {url}")
            releases = self.client.get_json_response(url)
            releases_data[name] = OamReleasesData(
                repo_url = repo.repo_url,
                archived = repo.archived,
                description = repo.description,
                releases = [
                    OamReleaseData(
                        prerelease = release.get("prerelease"),
                        tag_name = release.get("tag_name"),
                        name = release.get("name"),
                        published_at = release.get("published_at"),
                        html_url = release.get("html_url"),
                        body = release.get("body"),
                        assets = [
                            ReleaseAsset(
                                name = asset.get("name"),
                                size = asset.get("size"),
                                digest = asset.get("digest"),
                                updated_at = asset.get("updated_at"),
                                browser_download_url = asset.get("browser_download_url")
                            )
                            for asset in release.get("assets") if asset.get("name").endswith(".zip")
                        ]
                    )
                    for release in releases if isinstance(release, dict) and not release.get("draft")
                ]
            )
        return releases_data

    def process_release_zip(self, zip_url: str) -> tuple[list, AppSizingStat]:
        content_xml_paths = ['data\\content.xml', 'data/content.xml']

        response = self.client.get_response(zip_url)
        zipfile_obj = zipfile.ZipFile(BytesIO(response.content))

        app_stat = None
        hardware_info = None

        # Check for app xml to read parameter-memory-size
        xml_files = [name for name in zipfile_obj.namelist() if name.endswith('.xml') and name not in content_xml_paths]
        if len(xml_files) != 1:
            logging.warning(f"Found {len(xml_files)} other XML files in the archive {zip_url}, expected only one: {xml_files}")
        else:
            app_xml = xml_files[0]
            logging.debug(f"Analyse '{app_xml}' as App-XML")
            with zipfile_obj.open(app_xml) as xml_file:
                app_stat = AppSizingStat(xml_file)
                logging.debug(f"Sizing in '{app_xml}': {app_stat}")

        # needs to check windows-path as found in zip generated by OpenKNX-Build-Process
        content_xmls = [name for name in content_xml_paths if name in zipfile_obj.namelist()]
        if len(content_xmls) == 0:
            logging.warning(f"No 'data\\content.xml' or 'data/content.xml' found in the archive {zip_url}")
        else:
            # [[WORK-AROUND]] try to fix for wrong encoding, some releases contains utf-16le:
            try:
                with zipfile_obj.open(content_xmls[0]) as xml_file:
                    xml_content = xml_file.read().decode('utf-8')
            except UnicodeDecodeError:
                with zipfile_obj.open(content_xmls[0]) as xml_file:
                    logging.warning(f"((>>WORKAROUND<<)) 'content.xml' not UTF-8 encoded, try fall-back to wrong UTF-16LE: {zip_url}")
                    xml_content = xml_file.read().decode('utf-16le')

            # [[WORK-AROUND]] quick-fix for older releases with broken XML:
            xml_str = xml_content.replace('<Products>\r\n</Content>', '</Products>\r\n</Content>')
            if xml_str != xml_content:
                logging.warning(f"((>>WORKAROUND<<)) Quick-Fixed broken XML in 'content.xml' found in the archive {zip_url}")

            try:
                root = ET.fromstring(xml_str)
                hardware_info = [product.get('Name') for product in root.find('Products')]
            except ET.ParseError as e:
                logging.error(f"'content.xml' parsing failed in the archive {zip_url}")
                # TODO check hard ending?!

        return hardware_info, app_stat

    def process_releases(self, releases_data: dict[str, OamReleasesData]) -> tuple[dict[str, list[str]], dict[str, AppSizingStat]]:
        hardware_mapping = {}
        oam_stat = {}
        for oam, oam_data in releases_data.items():
            oam_releases = oam_data.releases
            if not oam_releases or not isinstance(oam_releases, list) or len(oam_releases) == 0:
                logging.warning(f"No releases found for {oam}")
                continue
            latest_release = oam_releases[0]
            for asset in latest_release.assets:
                ## TODO check all?
                logging.info(f"Fetching release archive {oam} from {asset.browser_download_url}")

                # cache results of process_release_zip: use filename as key inside of oam-directory:

                app_stat = None
                hardware_info = None

                # hardware_info, app_stat = process_release_zip(asset['browser_download_url'])
                out_dir = os.path.join("releases_data", oam)
                os.makedirs(out_dir, exist_ok=True)
                filename = asset.digest
                if not filename:
                    logging.warning(f"No digest found for asset {asset.name} in {oam}!")
                    # logging.warning(f"asset: {json.dumps(asset, indent=4)}")
                    filename = f"{asset.name}__{asset.updated_at}__{asset.size}"

                out_path = os.path.join(out_dir, f"{filename.replace(':', '_')}.json")
                if os.path.exists(out_path):
                    with open(out_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    hardware_info = data.get("hardware_info")
                    app_stat = data.get("app_stat")
                else:
                    hardware_info, app_stat = self.process_release_zip(asset.browser_download_url)
                    data = {}
                    if hardware_info:
                        data["hardware_info"] = hardware_info
                    if app_stat and False:
                        data["app_stat"] = app_stat

                    with open(out_path, "w", encoding="utf-8") as f:
                        json.dump(data, f, ensure_ascii=False, indent=4)

                if app_stat is not None:
                    oam_stat[oam] = app_stat
                if hardware_info is not None:
                    hardware_mapping[oam] = hardware_info
                    break ## TODO check

            else:
                logging.warning(f"No assets found for {oam}")
        return hardware_mapping, oam_stat
