# Build OpenKNX Release Overviews for Integration in Pages, Wiki and Toolbox
# 2025 CK (OpenKNX)

name: Update Releases

on:
  schedule:
    - cron: '29 */2 * * *' # Runs every 3 hours at h:29 (UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-releases:
    name: Update Releases Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install Jinja2
          pip install defusedxml

      - name: Run update releases script
        run: python scripts/update_releases.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
         
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            histlen=$(git rev-list --count HEAD)
            git commit -m "Update ~ $histlen"
            git push
          fi
