# Build OpenKNX Release Overviews for Integration in Pages, Wiki and Toolbox
# 2025 CK (OpenKNX)

name: Update Releases

on:
  schedule:
    - cron: '29 12 * * *' # Runs every day at 12:29
  push:
    branches:
      - main

jobs:
  update-releases:
    name: Update Releases Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install Jinja2

      - name: Run update releases script
        run: python scripts/update_releases.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add releases_list.html releases.json releases/ dependencies_table.html
         
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            now=$(date +"%Y-%m-%d %H:%M:%S")
            git commit -m "Update OAM Data ($now)"
            git push
          fi